// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJrnAluJb-p8uHCmP5WnK3__PP9TXF0Y',
    appId: '1:1059209286670:web:86153999ac09c057ab985f',
    messagingSenderId: '1059209286670',
    projectId: 'garbagecollection-e3d40',
    authDomain: 'garbagecollection-e3d40.firebaseapp.com',
    storageBucket: 'garbagecollection-e3d40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUNIgUT6fGqTQj8JJM2i_RCHxGzHPPplQ',
    appId: '1:1059209286670:android:b7217b8c66f5ef5aab985f',
    messagingSenderId: '1059209286670',
    projectId: 'garbagecollection-e3d40',
    storageBucket: 'garbagecollection-e3d40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSH7Ra7rC1TGbOZR75nL0OxcSDDRXCwtY',
    appId: '1:1059209286670:ios:50f92f81e37c3b75ab985f',
    messagingSenderId: '1059209286670',
    projectId: 'garbagecollection-e3d40',
    storageBucket: 'garbagecollection-e3d40.appspot.com',
    iosClientId: '1059209286670-0iskpntdiigrujb1ghk2jb3jdhe76n4f.apps.googleusercontent.com',
    iosBundleId: 'com.example.garbageCollection',
  );
}
